# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

services:
  isaac-lab-base:
    volumes:
      - type: bind
        source: ../../XRoboToolkit-Teleop-Sample-Python
        target: /workspace/XRoboToolkit-Teleop-Sample-Python
      - type: bind
        source: ../../XRoboToolkit-PC-Service-Pybind
        target: /workspace/XRoboToolkit-PC-Service-Pybind
      - type: bind
        source: ../../XRoboToolkit-PC-Service
        target: /workspace/XRoboToolkit-PC-Service
